# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-and-test:  
    docker:
      - image: cypress/base:14.15.0
    environment:
      context: learning
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: |
            npm run delete:reports && npm test && npm run create:reports 
      - persist_to_workspace:
          root: ~/
          paths:
            - mochawesome.json  
  print-results:
    docker:
      - image: circleci/alpine@latest
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: print results
          command: |
            for file in $(ls *.json); do cat $file; done

workflows:
  run_cypress_tests_and_print_results:
    jobs:
      - build-and-test
      - print-results
          requires:
            - build-and-test