version: 2.1
jobs:
  build-and-test:  
    docker:
      - image: cypress/base:14.15.0
    environment:
      context: learning
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: |
            print_pipeline_id
            npm run delete:reports && npm test && npm run create:reports 
      - persist_to_workspace:
          root: ~/
          paths:
            - mochawesome.json  
  print-results:
    docker:
      - image: circleci/alpine
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: print results
          command: |
            for file in $(ls *.json); do cat $file; done

commands:
  print_pipeline_id:
    description: prints pipeline ID
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

workflows:
  run_cypress_tests_and_print_results:
    jobs:
      - build-and-test
      - print-results
          requires:
            - build-and-test