version: 2.1
orbs:
  node: circleci/node@4.0.1

jobs:
  build-and-test:  
    docker:
      - image: cypress/base:14.15.0
    environment:
      context: learning
    steps:
      - checkout
      - node/install-packages
      - print_pipeline_id
      - run:
          name: Run tests
          command: |
            npm run delete:reports && npm test && npm run create:reports 
      - persist_to_workspace:
          root:   /
          paths:
            - /root/project/mochawesome-report/* 
  print-results:
    docker:
      - image: alpine:latest 
    steps:
      - attach_workspace:
          at: /
      - run:
          name: print results
          command: |
            ls
            
commands:
  print_pipeline_id:
    description: prints pipeline ID
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

workflows:
  run_cypress_tests_and_print_results:
    jobs:
      - build-and-test
      - print-results:
          requires:
            - build-and-test
      